### ISSUE TITLE
Support lists in container field

### ISSUE THREAD

**Issue by Aceplante** [vectorwing/FarmersDelight#1002]
### Minecraft version

1.18.2

### Farmer's Delight version

latest

### NeoForge version

latest?

### Description

The container field of recipes does not seem to support lists, which makes sense, but would be appreciated if it would be easy to implement.

### Mod list

N/A

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
This has been discussed in the past. The container slot doesn't support tags or item lists because items in Minecraft can only ever be contained by one specific kind of item. Allowing various items would potentially cause container "mutation" when the meal is consumed, which is technically broken behavior.

For example: a meal whose container is a **Bowl**, but can be served on a "coconut shell", would convert the shell into a wooden bowl when the meal is consumed.

I have yet to decide if trusting modpack makers with this power is worthwhile, as FD itself has no use for this feature.
