### ISSUE TITLE
The server Crashes non stop

### ISSUE THREAD

**Issue by JENADAM1234** [vectorwing/FarmersDelight#1004]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### NeoForge version

forge-47.3.10

### Description

I Cooked a stuffedt hoglin on my friends minecraft server and the server crashed and everytime it gets turned back on it crashes again.

### Steps to reproduce

Cook a stuffed hoglin

### Mod list

Its in the logs

### Logs

[crash-2024-10-24_20.52.24-server.txt](https://github.com/user-attachments/files/17514228/crash-2024-10-24_20.52.24-server.txt)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
This seems to be an error related to the **PMMO Farmers Delight Compat** mod. It adds a mixin to the Cooking Pot class so that it posts an event for PMMO, but it doesn't seem to be working on the version you have.

Either way, it's not related to FD itself. I suggest updating both PMMO and this compat mod, to see if the issue has been fixed. If not, you can forward this issue to the addon author here:

https://github.com/Silvertide7/pmmo_farmers_compat/issues
