### ISSUE TITLE
[Suggestion] A config option to disable the strength and nourished status effects from their respective foods.

### ISSUE THREAD

**Issue by Inpaladin** [vectorwing/FarmersDelight#102]
Title.  Feels kind of strange having the option to disable the jump boost and comfort effects but not the strength or nourished ones.  I also personally feel that having a food give strength and have the ability to be stacked x64 with marginally better saturation than golden carrots is a bit overpowered when compared with the other foods the mod has to offer, but that would obviously be solved with a config option allowing easy disabling of the strength effect.

**Comment by vectorwing** [comment]
Thanks for the balancing feedback! =)

"Finger foods" giving burst effects was originally an experiment to see if they would attain niche uses, such as a pick-me-up during combat after enduring damage.

All FD foods are designed to be generally superior to a Steak or a Golden Carrot, as they require the player to maintain several different farms to make; that said, I am looking into feedback as to the different effects of each food, how strong or broken they are, and how they compete against each other for the player's interest.

As for a config, I haven't done so yet due to lacking knowledge. Comfort has one because it's event-based and messes with vanilla items. This might be an enhancement for a next version, if I can figure out a way to cancel item properties.

**Comment by Inpaladin** [comment]
Thanks for the response!  I totally get that the foods of this mod are meant to be much more powerful than the vanilla foods, but I guess what I was trying to say was that the strength food is incredibly good on it's own without the strength buff, even if it's saturation/hunger is worse than some of the other foods due to it's stack size.  Strength is kind of ridiculous in vanilla minecraft, maybe you could shorten the buff if you think it should stay?  I don't know.  Fantastic mod regardless, can't wait to see what's in store for the future!

**Comment by Inpaladin** [comment]
As for the config thing, I am not at all knowledgeable in the forge api or really anything minecraft when it comes to programming, and this could be an extremely useless suggestion, but would it be possible to create an array that contains the potion effects used for the items, have the specific potion effects granted by the items use a reference to the array element instead of just the effect as text, and have the config allow you to just set the array element to a certain value, with one being blank for disabling the effect?

**Comment by vectorwing** [comment]
Closing this suggestion, as I'm moving these over to the Discussions tab. 👍 

I'm still thinking about ways to allow this to be a config, but since it's on registry time, nothing came up yet.
