### ISSUE TITLE
[Question] Is possible to add Tree Bark Drop when you strip a log in the world? 

### ISSUE THREAD

**Issue by ffuentesm** [vectorwing/FarmersDelight#1023]
Is it possible to cause Tree bark to drop when you right-click on a Log with an Axe?
The cutting board recipe is nice for the automation of tree bark, but I was wondering if the Log Strip interaction could cause the Tree Bark to drop too.

**Comment by vectorwing** [comment]
I chose not to make bark drop from in-world stripping, because this would create a lot of item spam for builders.

Even if players are interacting with FD, they might not want Tree Bark for paper or composting when building their house. The Cutting Board, in this case, acts as an opt-in route for bark.

**Comment by BarchamMal** [comment]
Not that it matters, but what if you sneaked while stripping bark?
