### ISSUE TITLE
Can´t plant anything on vanilla minecraft "farmland" blocks

### ISSUE THREAD

**Issue by Fidulus** [vectorwing/FarmersDelight#1025]
Version: 1.21.1 - Java
Prism-Launcher, lots of other mods

I am not sure if it´s just me or an issue related to another mod. But because I´m not very good in knowing what might be wrong I´m here to ask the pros if you might know.

The title says it all. Either finding "minecraft-farmland-blocks" roaming around the world or creating them myself i am not able to plant anything on it, regardless what seeds or fruit.

When i am using the blocks from Farmer´s delight, all works flawlessly. Rich soil block put down and i can plant everything i want on it.

My modlist in total:
https://pastebin.com/pgwNhegX

Latest.log:
https://pastebin.com/9cQLnQ76

Log:
https://pastebin.com/wc7wXK6d

If you need any other information just tell me. Thank you for your  time and looking into this. :-)

**Comment by vectorwing** [comment]
Farmer's Delight doesn't modify normal farmland, so it's unlikely that the issue is related. The logs also don´t show any relevant info, sadly.

For cases like this, the best you can do is a binary search:
1. Disable half of your mods and reboot the instance in a test world
2. If the issue persists, disable half of the remaining mods, and try again.

This will help you narrow down which mod is responsible for the bug. Maybe you have some mod which tampers with crop growth and planting, like a seasons mod?

**Comment by Fidulus** [comment]
@vectorwing Thank you very much for your time and effort. <3
I´m very sorry for suspecting farmersdelight to be the culprit 😅
Going to investigate as you suggested. Please have a great week and some pre-holiday-wishes

**Comment by vectorwing** [comment]
Don't worry about it! It's a reasonable expectation. :smile: 

I mention because the mod indeed doesn't change farmland behavior. Either way, if it turns out FD is related to the issue, feel free to reopen it, and we can look further into the cause. 👍

Happy Holidays to you as well!
