### ISSUE TITLE
How does one add a tool to the cutting board tool action list? 

### ISSUE THREAD

**Issue by ffuentesm** [vectorwing/FarmersDelight#1035]
I am trying to add the saw from Silent Gear to work with the cutting board to get bark.
Looking at the recipe file, it uses the: 
    "type": "farmersdelight:item_ability",
    "action": "axe_strip"

How does one add the axe.strip to the saw? 
![image](https://github.com/user-attachments/assets/cd837d18-b2eb-4e28-8eec-17af15f3e44a)

From what I am seeing, the saw is already part of the axe_dig action on other curring recipes. 
![image](https://github.com/user-attachments/assets/95acafb4-8097-4478-afeb-6eacacb24419)

From what I can see, the saw already has minecraft:axe tags on it.
![image](https://github.com/user-attachments/assets/e5c2fe9c-e929-47c3-87ed-5f352aafefd5)

**Comment by vectorwing** [comment]
Tool actions are added in-code, so you would need the Silent Gear dev to add this action; I assume they decided not to intentionally. Otherwise, you would need an add-on for it, can't be done through datapacks.

There is a possibility that I might create a "fallback" tag for this type of ingredient sometime, but it's not currently planned.

Also, for future references: please open a **Discussion** for this type of question next time, as this board is only for issues.
