### ISSUE TITLE
[1.16.4] Bacon is being replaced Pork Cuts from some assembly required

### ISSUE THREAD

**Issue by SpycrabSXL** [vectorwing/FarmersDelight#133]
**Description**
When using chopping raw porkchop on a cutting board it turns into Pork Cuts from some assembly required as they use the same recipe.

**Steps to reproduce:**
Not sure whether installation order will affect which one is produced but
1. Download some assembly required https://www.curseforge.com/minecraft/mc-mods/some-assembly-required/files/3171267
2. Download farmers delight https://www.curseforge.com/minecraft/mc-mods/farmers-delight/files/3172073
3. Make a cutting board, any knife from either mods and get some raw porkchop
4. Chop porkchop with knife
5. Porkchop turns into Pork Cuts

**Expected behavior:**
Chopping raw porkchop on the cutting board should produce bacon.

**Screenshots**

Bacon
![image](https://user-images.githubusercontent.com/70557842/104893059-ea4c1100-59ad-11eb-876e-fca4a735c7be.png)

Porkcuts
![image](https://user-images.githubusercontent.com/70557842/104893131-fb951d80-59ad-11eb-99b4-b2f535565f8c.png)

**Mod list:**
Post a list of your mods here, **Forge and Farmer's Delight versions are mandatory!**
You can generate a mod list by forcing a crash. In your game, hold F3+C for 10 seconds, then check your logs; the list of mods will be by the end.

[crash-2021-01-18_09.54.10-fml.txt](https://github.com/vectorwing/FarmersDelight/files/5828971/crash-2021-01-18_09.54.10-fml.txt)

Thanks for making this cool mod :D

**Comment by vectorwing** [comment]
Hmm, good catch!

I'm taking a look at Some Assembly Required now, and oh my goodness, what an awesome mod! The whole idea of putting a big ol' sandwich together is really cool. x)

Seems like they added FD integration on their end for their sliced ingredients, which is very cool. This happens to include their pork cuts item, which before 0.3 was an uncontested Porkchop cutting recipe; so it's causing a small overlap now. 😄

We might have to contact the dev to perhaps remove that one recipe from FD's cutting board, so that both items are obtainable in their respective boards. But since we're here already, perhaps I could go so far as to make some "sandwich layer" sprites for FD ingredients as well, to integrate with SAR further! I'll check this later. 👍

**Comment by ochotonida** [comment]
I'll release a patch for Some Assembly Required which fixes this issue sometime in the following days 👍 
Edit: Patch released!
