### ISSUE TITLE
Stove Overhaul? (Campfire Overhaul + Farmers Delight's Stove)

### ISSUE THREAD

**Issue by slainless** [vectorwing/FarmersDelight#162]
For "immersion" purpose, can i request for a feature? I would like to see cross-compat and interaction with [Campfire Overhaul](https://www.curseforge.com/minecraft/mc-mods/campfire-overhaul)

Basically, make stove work the same way as campfire from CO when it's installed? Honestly, i don't know if i should open an issue here or CO's repo.

**Comment by vectorwing** [comment]
Looking over at the mod page, I could spot a few things different that could be integrated, but nothing very explicit. Do you have anything in mind for similar behavior?

I might sometime introduce some stove settings, such as a "require fuel" mode, or a config for it to start unlit. Thing is, since it's not technically a Campfire, it can't inherit changes done to the Campfire block itself.

**Comment by slainless** [comment]
Ah yes, actually,,, the only thing and the main thing that i suggest to be integrated is fuel system.

But... i'm aware of the limitation as well. At the time when i opened this suggestion, i thought that you can just extend CO fuel system and implement it to FD' stove. But, after skimming thru CO code, it seems that CO code targets campfire block class directly, and most of it's method is tied to campfire block, just like what you said. Maybe integration will be easier to implement if CO code is more abstract. But, independent feature for fuel system is also fine with me 👍 .

**Comment by vectorwing** [comment]
This mechanic is being considered for a future release, but I'll need to test it thoroughly before confirming anything. I'll close it now, since it's on my board. 👍

**Comment by Jurklein** [comment]
How is this going?

Stoves starting lit are too much of an overpowered state. For hardcore modpacks, the default unlit state (and requirement of fuel as a plus) is preferrable.
