### ISSUE TITLE
[1.16.5] [Enhancement] JEI for Knives, Straw Harvesters

### ISSUE THREAD

**Issue by Nerdpie** [vectorwing/FarmersDelight#185]
I am helping with the development of Mischief of Mice's "Magical Mischief Tour" pack.  The pack currently has version 0.3.2 of Farmer's Delight.

I wanted to try making the basket, but the only way to get straw that is visible in JEI is using rice on the cutting board.  However, looking at your documentation here, I found that I could break grass-type blocks with a knife for a chance to get straw.  I would suggest an additional JEI handler - or at least a tooltip or JEI info page - noting that straw can be obtained this way, to improve discoverability.

I have not investigated the "guaranteed new drops from slain animals" behavior; does this mean if the mob is killed using the knife?  My mind went straight to Vallen's Vintage Story streams, but that would entail creating a different entity altogether.  This is another feature that could benefit from improved discoverability, be it through JEI or another method, such as a Patchouli guide.

P.S.  It may be worth adding enhancement/feature request and question templates to the repo.  Just a thought.

**Comment by vectorwing** [comment]
Hey there!

Farmer's Delight explains/hints its progression through the **Advancements** tab. There are some detailing how to obtain straw, knife behaviors, Rich Soil creation etc.

I understand not all players even bother reading them, but since they're the vanilla method of hinting progression, I chose to use them instead of yet another guidebook.

I did consider introducing some JEI descriptions with the advancement texts, to aid players a bit, but I'm still experimenting.

**Comment by Nerdpie** [comment]
Ah, fair enough; admittedly, I often forget about checking the advancements.  If only vanilla would integrate 'Better Advancements' so we could scroll better, have it fit, etc. ... >_> b But, that's a rant for elsewhere!

We do have JEI Tweaker in the pack, so I can add the description pages that way, at least for now.  I'll leave whether to close the issue, or keep it open for visibility, to your discretion.

**Comment by vectorwing** [comment]
I added a JEI description box for Straw, with a similar text to the one in the corresponding advancement. Still thinking whether other ones would fit, but this will do for the time being until I can decide on it. Thank you for the suggestion, and also for featuring FD in your modpack! 😄

Also, regarding a suggestion template - I don't particularly mind suggestion issues being informal and loose with their format. The template exists for bug reports because those benefit heavily from the extra details, and not every user defaults to providing them. But thanks anyway!
