### ISSUE TITLE
[1.16.5] [Enhancement] Tetra Compat

### ISSUE THREAD

**Issue by Nerdpie** [vectorwing/FarmersDelight#186]
I am helping with the development of Mischief of Mice's "Magical Mischief Tour" pack. The pack currently has version 0.3.2 of Farmer's Delight.

Tetra adds in a 'sickle' tool type.  While I have not researched it, I imagine that tags cannot be applied to items strictly based on NBT variants.  If possible, it would be useful to have tools with at least one side of the head being a sickle function as `farmersdelight:straw_harvesters`.

Any additional integration - such as the machete or short blade weapons acting as knives - might be desirable in some packs, but would probably need a config toggle, as I could see where some packs might want such behavior, but others might now.

**Comment by Nerdpie** [comment]
... and now I glanced at the PRs and saw that Mickelus submitted a PR already, #122 .  I'm on a roll... :facepalm:

**Comment by vectorwing** [comment]
ToolTypes are a bit hard to expose to data-driven customization. I'm aware that Tetra tools use NBT for their identity, which prevents them from being good tag targets; that said, I'm still thinking about mickelus' PR, and the idea of standardizing some ToolTypes for game logic. Not sure yet, though.

**Comment by StrangerSon71** [comment]
Do you think you might get around to this now that 0.5 is out?

**Comment by vectorwing** [comment]
I tried a few times, but ran into a few problems getting it to work. For a custom Tetra tool to be FD-compatible, I will probably have to rewrite the way knives interact with the mod entirely, since right now it's all tag-based. Also, adding the ToolTypes Tetra expected didn't work, for some reason.

This might be my next focus coming up, together with some other tweaks.

**Comment by augustofuneq029** [comment]
Buen mod

**Comment by augustofuneq029** [comment]
Aaaaahhhhhhhh

**Comment by vectorwing** [comment]
Gee, I sure left this one in the dust, didn't I? Funny enough, since it's a suggestion, I should have moved it to Discussions.

Anyway: I have discussed this with mickelus recently, and it seems he already created an add-on for Tetra which accomplishes this integration, called [tetracelium](https://www.curseforge.com/minecraft/mc-mods/tetracelium)! You can get it for 1.20.1, and possibly future versions too.

I'm likely going to add a few changes to FD to facilitate tetracelium's features soon.
