### ISSUE TITLE
[1.16.5] Cooking Board recipes use wrong items

### ISSUE THREAD

**Issue by NielsPilgaard** [vectorwing/FarmersDelight#206]
**Description**
The Cutting Board accepts Armor from the mod Better End in recipes that require an axe

**Steps to reproduce:**
I looked in JEI, can be replicated.

**Expected behavior:**
I expected only axes to be valid in axe recipes

**Screenshots**
![image](https://user-images.githubusercontent.com/20716525/109215651-c00f1f80-77b3-11eb-8ade-bd76506fd596.png)

**Mod list:**
- Forge-1.16.5-36.0.40
- FarmersDelight-1.16.3-0.3.2
Modlist: https://github.com/NillerMedDild/Enigmatica6/blob/master/MODLIST.md

**Comment by vectorwing** [comment]
That sounds like a wacky integration that went wrong. Either someone tagged these chestplates as `forge:tools/axes`, or the chestplates somehow have the axe ToolType...

Is it happening exclusively to BetterEnd armor?

**Comment by NielsPilgaard** [comment]
BetterEnd Armor and the Quark Pickarang I believe :) 
Edit: No strange tool tags on the armor :P

**Comment by vectorwing** [comment]
And I couldn't verify ToolTypes either; their repo doesn't seem to have Terminite and Thallasium armors (the ones that became usable in the board) registered on their ModItems. The other two armor materials seem to be fine, though, and can't be used as axes.

This is kinda puzzling... I may have to dig deeper. Maybe the BetterEnd devs might be able to help?

**Comment by vemerion** [comment]
It is a bug on our part. [In this class](https://github.com/Beethoven92/BetterEndForge/blob/master/src/main/java/mod/beethoven92/betterendforge/common/block/material/MetalMaterial.java) you can see the registration of the Terminite/Thallasium items, and as you can see, we use the same instance of Item.Properties for every item, which means that the armor will get every tool type, since the tooltypes are added to the Item.Properties instance in the constructors of the various tool item classes (AxeItem, PickaxeItem etc).

**Comment by Beethoven92** [comment]
NIce find Vemerion, this was a very subtle issue! It now can be fixed very easily

**Comment by vectorwing** [comment]
Good to know the cause was found! Thanks for the help! 😄
