### ISSUE TITLE
[Suggestion] Soybeans and Soymilk/Tofu as animal product alternatives

### ISSUE THREAD

**Issue by kingpls** [vectorwing/FarmersDelight#216]
Kinda like how they're implemented in Pam's Harvestcraft. Tofu would probably need to be combined with several spices/ingredients to make the meat alternatives just to balance out with actual meat itself, but overall, it would be nice to have vegan options in the game.
(Also stuff like dessert tofu and asian dishes involving tofu would be cool to see as well aha)

**Comment by vectorwing** [comment]
Soy was briefly considered, but since its primary use would be Tofu, I ended up not favoring it. Vegan and vegetarian recipes are added from time to time, but I'd rather try to use less "meat substitutes" and instead highlight recipes that are about the vegetables themselves.

Thanks for suggesting, though! 😄
