### ISSUE TITLE
[Suggestion] Carrot Cake

### ISSUE THREAD

**Issue by moon-st0ne** [vectorwing/FarmersDelight#217]
Carrot cake is an obvious choice given carrots are already a vanilla food. The recipe would be identical to the vanilla cake recipe, with one of the wheat replaced with a carrot, or it could use the FD pie format somehow for a more accurate ratio of carrots to wheat. The amount of hunger restored would be either on par with or just slightly higher than a vanilla cake, probably higher as it is marginally healthier.
When placed, it would have a carrot-orange base and a glazed layer of cream cheese on top, perhaps with some kind of decorative carrot topping. It could be cut into 7 slices like a vanilla cake.

**Comment by vectorwing** [comment]
Carrot Cake was considered, as I have yet to explore cake flavors. However, we have a fun dilemma regarding its topping.

You see, I'm from Brazil, and here we have a very dear (although much simpler) way of making carrot cakes, with a chocolate ganache topping. This is different from the "american" carrot cake, which is both darker and uses cream cheese glaze.

So I'm kinda divided between which one to go for, since my favored option will draw curious questions from overseas players. 😆 But it might happen someday, who knows.

**Comment by moon-st0ne** [comment]
Personally, I vote chocolate ganache. It's always way cooler to see other peoples' regional recipes for things.

**Comment by SynfulChaot** [comment]
There's always the option of having both frostings being available depending on which ingredients are used.

**Comment by moon-st0ne** [comment]
Ever come to a decision?

**Comment by vectorwing** [comment]
Nothing confirmed, but cakes might show up eventually. Thanks for suggesting!
