### ISSUE TITLE
Other auto farming mod doesnt detect farmers delight crops

### ISSUE THREAD

**Issue by kihgy** [vectorwing/FarmersDelight#221]
I tried having Minecolonies farmer and rats to harvest, but they dont recognize the crops.

**Comment by kihgy** [comment]
Also straw golems

**Comment by buttpooper23** [comment]
![enker](https://user-images.githubusercontent.com/80023047/110736750-ce1c6180-81f1-11eb-86cb-c6b0d8fa2bfd.PNG)
![craft](https://user-images.githubusercontent.com/80023047/110736753-cf4d8e80-81f1-11eb-8647-cd4034c4cb21.png)
![otto](https://user-images.githubusercontent.com/80023047/110736758-d07ebb80-81f1-11eb-8490-dcee69c9923e.jpg)
![unknown](https://user-images.githubusercontent.com/80023047/110736766-d379ac00-81f1-11eb-9274-422210799202.png)

**Comment by buttpooper23** [comment]
FAKE

**Comment by buttpooper23** [comment]
UR A LIAR NOT REAL

**Comment by vectorwing** [comment]
Sorry about the above user's spam content, I deleted the messages.

As for the issue: are you planting crops above Rich Soil? Compatibility issues can arise on these interactions, and there's a possibility some mods don't recognize Rich Soil Farmland as a valid ground for farming. I'll do some testing later.

**Comment by kihgy** [comment]
No I was planting them on vanilla farmland

**Comment by vectorwing** [comment]
@kihgy Sorry for the delay.

I need further info to check on this issue. Please provide your mod list (including FD and Forge), and answer the questions below:

1. Are these farming methods not recognizing **tomatoes** in particular, or are they failing with every crop?
2. Can they interact with the upper side of Rice crops?

I checked with some MineColonies users, and the only crop that seems to fail is the tomato, which is expected. If *all* crops are failing, I need to check further.

**Comment by vectorwing** [comment]
I ran some tests on the mods for both this issue and #227, and it largely boils down to these mods requiring crops to be `instanceof CropsBlock` rather than checking for their age and `IGrowable`. Unfortunate...

**Rats:** They glitch out trying to break tomatoes and the _underside of Rice_, causing a rapid seed duplicating glitch. Might be more on their end, though;
**MineColonies:** The crop needs to be textbook like a vanilla crop for Farmers to make use of them. I haven't tested Planters yet, though I expect them to not work with Tomatoes, Rice or Sweet Berries.
**PneumaticCraft:** Works with Rice, ignores Tomatoes.

Again, this is an issue, as making Tomatoes a CropsBlock makes simple-harvesting mods disrupt their plucking mechanic. Though in this case, the trade-off is very large; being able to auto-farm Tomatoes matters more. I might convert them back to a CropsBlock sometime.

**Comment by vectorwing** [comment]
Tomatoes might receive a strategic redo later down, to address both sides of this issue.
I'll be closing it for now, but it's marked for consideration. Thanks for the help!
