### ISSUE TITLE
Tomato isn't detected as a crop

### ISSUE THREAD

**Issue by fertil20** [vectorwing/FarmersDelight#227]
I tried having Harvesting Drones by PneumacticCraft to harvest and plant crops. Onion and cabbage goes fine, but the tomato doesn't. They are just getting ignored

**Comment by vectorwing** [comment]
That may be a technical limitation.

Tomato crops don't inherit the `CropsBlock` class because Quark and other mods override its plucking mechanic with right-click harvesting by default. I haven't checked, but chances are PneumaticCraft drones only check for blocks that inherit `CropsBlock`, instead of checking the `AGE` blockstate, which all growable blocks would have (including sweet berries).

Considerations to make Tomato crops a CropsBlock again are underway, but not much I can do right now.

**Comment by vectorwing** [comment]
Closing this as it's related to #221.
