### ISSUE TITLE
[1.16.5] Most feasts do not properly update their hitboxes

### ISSUE THREAD

**Issue by Feranogame** [vectorwing/FarmersDelight#243]
Most feasts do not have their hitboxes updated throught the eating process, only vanilla cakes.

**Comment by vectorwing** [comment]
This is intentional, due to limitations with hitbox facing.

The hitbox of a block cannot be rotated. For the feasts and pies to have a matching hitbox, we would need one for each of the 16 state combinations, with some being compost hitboxes, which would mean a lot of data for a block like such. On the plus side, a larger hitbox makes it easier to interact with the block.

Not much I can do, sorry. :(
