### ISSUE TITLE
Subtitles for harvesting tomatoes say "Berries pop"

### ISSUE THREAD

**Issue by PaperfishStudios** [vectorwing/FarmersDelight#245]
either i now learn that tomatoes are berries or this is a leftover from copying the sweet berry sfx

**Comment by vectorwing** [comment]
Yes, they are berries! Though no, that subtitle is not intentional; I merely borrowed the sound event, not realizing subtitles are tied to them. I actually did clone some sound events for the stove before (campfire sounds), to explicitly give them a custom subtitle.

Not sure whether to change it in this case, though.

**Comment by vectorwing** [comment]
I added a custom subtitle for Tomato Crops on commit 156a0bc. 👍
