### ISSUE TITLE
(extremely large and rambling suggestion) The Oven

### ISSUE THREAD

**Issue by pm065** [vectorwing/FarmersDelight#249]
First of all, thank you for a farming and cooking mod that feels and looks amazing and vanilla-like. This is a pretty long suggestion (well, it's two suggestions, but the first takes most of the space as it is far more complex), and it would likely take a while to implement one, let alone both of these so I do not blame you at all if you decide not to accept this.

I always found it odd how vanilla foods were crafted in a _crafting table_. I'm extremely glad that Farmer's Delight adds a much better and more logical cooking system, but items like bread and cakes are still made in a crafting table. It probably makes a tiny bit more sense than moving them to a cooking pot, but still. That's why I came up with the idea of the oven, and a bit later while I was still thinking about FD I came up with another, simpler idea; the millstone.

**The Oven (and everything that goes with it)**
The oven would be a two-block-tall crafting station used to bake items like bread, feast items and cake. The oven's GUI would have one slot at first, into which you can insert Raw Dough, a Pie Crust, a Filled Cake Tin or a Bowl. Once you insert it, a couple more slots would appear; a fuel input, an output and an additional two slots if the Filled Cake Tin, one if the Pie Crust is added, or five if the Bowl is added to the starting slot.

The old recipes for these items would be removed by default (e.g. you can no longer make Cake or Bread in a crafting table) with an option to disable the change.

Feast oven recipes would be pretty straightforward; drop in the bowl, the fuel and the ingredients, and wait.

Cake would be a bit more complex to make. You would need to make a Filled Cake Tin using eggs, wheat (or flour if the second suggestion is accepted), milk, sugar and a Cake Tin, crafted with a few iron ingots. (If the carrot cake suggestion #217 is ever added, then for that you would need a special kind of cake mix with the same recipe except you also need two carrots) Then, you drop it in the slot. The two new slots that appear are for the Topping and the Icing. A bowl of icing would be made using sugar surrounding a bowl. (#217 would use a different kind of icing.) 
For the vanilla Cake, the topping is Sweet Berries, (and carrot cake if added would use something different) but of course modded cakes would be able to use different ones.
This process would finally make a Cake (to make up for it, cake could be buffed with a config option to disable said buff).
You of course would get the Cake Tin back after you finish baking.

The process to make Pumpkin Pie and other pies would be kind of similar to cake. You need a pie crust, crafted with the same recipe as the cake tin except replacing iron ingots with wheat. Unlike the cake tin, you do not get it back when you finish.
Once you add the pie in, you can put a pumpkin or another choice of filling in the filling slot.

Bread would simply be made by dropping Raw Dough into the oven slot.

Again, I will in no way be offended if you just say 'nope, sorry, would take too long' and close the issue. I recognise that mod developing takes time, which unfortunately is sometimes hard to get when you want it (:

**Comment by AbbyGrail** [comment]
I don't think it is a good idea to use plates instead of bowls in the crafting recipe, Minecraft is not just about logic, it's about gameplay value too. see how there's no wax and honeycomb is used to craft candles in 1.17, or how you can craft sugar canes straight into paper and sugar, or how you can craft the netherite alloy without needing any heat. there's no need for a recipe to make sense.

The same thing goes for the millstone, wheat can be crafted straight into bread for the sake of simplicity, but FD adds dough, which has a more frustrating recipe but rewards you with 3 times more bread.

I like the idea of the oven tho, moving all the placeable food recipes (cakes, pies, and feasts) into a new crafting station.

**Comment by pm065** [comment]
I guess that's true, you can't really expect logic in a game with floating cubes, an infinite world and monsters that explode behind your back. 
I'll see if I can edit it to be more simple. The millstone was really just an extra thing tacked on to the end, so I feel no pain in removing it.
> (cakes, pies and feasts)

I forgot about pies! I thought I was missing something! Probably not entirely realistic, but the pies could be crafted almost the same way as the cake. Maybe you could make a pie crust and slap it into the oven with a filling? Probably makes no sense at all, but who cares? Better than making it with a hammer and chisel on a wooden workbench where you also make swords.

**Comment by vectorwing** [comment]
Hey there! Glad you're enjoying the mod, and thanks for the detailed suggestion. ^^

**Regarding Ovens**
Ovens did cross my mind at one point, primarily for baked goods. However, I would have to remove the ability to craft them for it to make sense, which is something FD explicitly avoids. The Oven block thus suffered from two issues:

- It didn't add much to the crafting process. For example: the pot can hold otherwise hard-to-stack meals and store 64 of them without using bowls before serving, being more interesting than crafting tables;
- It ran the risk of being a clone of the cooking pot, just with an explicit fuel requirement.

With FD, I didn't want to modify the vanilla gameplay directly, but rather try to add on top of it, filling gaps when possible, and basing much of the design on vanilla ideas. This is because such subtractive changes are often intrusive and hard to detect the source of; it's best achieved by a mod that makes it clear they're about doing the change, rather than a mod with a different premise (even if it would make sense in theme). Sure, I'd love a simple Oven to bake a cake or cookies instead of crafting them raw, but I haven't spotted a satisfying way to do that in this scenario yet.

Also, your description of the oven process seems very convoluted in some areas: requiring wood _and_ coal, specific slots for each part of the item, separate interfaces for each type of baked good... Those might be overkill for these items, considering they're not that strong of a consumable. Were the block to exist, I'd probably take a much simpler approach akin to how vanilla does it.

**Regarding Plates**
Yeah, I actually tried to avoid having separate Plate items, mostly to avoid clutter and micro-management. In a similar vein to how Glass Bottles change shape depending on their potion type, I had Bowls change to wooden plates to visually indicate a nourishing meal item (or a dog bowl). I feel making new containers for each thing would not add much to the process.

**Regarding Millstones**
Also considered briefly in the past... but it has the issue of being a one-trick pony for something already done in easier ways, or done far better by mods which make more use of it (e.g. Create). I didn't have many millable items to justify implementing my own millstone, or even a Mortar and Pestle for that matter.

It's important for items to represent a revelant step in crafting. Flour's most relevant application would be to make Wheat Dough (which I did with just Wheat and Water), but it would otherwise be an added step that is hard to automate. Vanilla often takes step-skipping too far, and I agree there, but sometimes it works in favor of crafting flow.

Thank you for taking your time to elaborate on your suggestion, btw! Sorry if this post sounded negative; I appreciate the discussion. :+1:

**Comment by pm065** [comment]
Yeah, now that I look at it again, it does look a little convoluted... Hmm. Maybe I could try to think of a way for the slots etc to be more universal, and I will change the bit where you need wood and coal - I don't know what I was thinking then (:

**Comment by pm065** [comment]
By the way, how do you add those coloured tags like 'Suggestion' and 'Bug Report' to the end of the name? I can't figure out how.

**Comment by jengendler** [comment]
+1 for an oven that makes sense for gameplay. It always feels like it's what's missing when I play with this mod. I love that your bread dough recipe is more tedious but yields higher quantities of bread, thus not making the vanilla recipe obsolete. That vanilla-friendly aspect makes this mod strong. I love that the smoker is a great way to cook food over a furnace simply because it's faster. I almost wish it was actually an oven, but it makes sense as it is, because it's the fisherman profession block. A baker would be an awesome profession to add to the game if an oven was introduced, but I digress. 

If an oven was introduced in this mod, one of the ways I could see it adding value to the game without overriding anything vanilla is to have it be slower than a smoker, but have an unlimited campfire flame used as its infinite fuel source. That would be the simplest version I can think of. This doesn't invalidate the smoker block, as that is a profession block with an inexpensive crafting recipe (whereas Farmer's Delight's stove recipe uses brick, I'd assume the over would be similar).

**Comment by vectorwing** [comment]
I'm cleaning up the issues board, and closing "suggestion" issues for the time being. If you'd like to continue this idea, please reopen it on the new **Discussions** page; that's where suggestions should be posted from now on. 👍
