### ISSUE TITLE
[Suggestion] Pam's HarvestCraft integration

### ISSUE THREAD

**Issue by Mnigos** [vectorwing/FarmersDelight#266]
Just a integration with Pam's mods

**Comment by DaLumma** [comment]
Really descriptive suggestion.

What integration are you asking for? They should be compatiple due to FD using forge tags for it's recipes. If phc doesn't use those tags it's a problem on their end.

Or do you want exclusive meals? That will probably not happen on vectorwings end.

**Comment by Mnigos** [comment]
I mean they should be compatiple due to FD using forge tags for it's recipes. You have to use some items from FD to create fe. spaghetti from Pam's

**Comment by vectorwing** [comment]
Both mods are currently integrated with each other through tags in their recipes. Ingredients from FD can, for the most part, be used in HarvestCraft 2 recipes, and vice-versa.

If you mean integrating HC2 meals in the Cooking Pot, I ended up not doing so due to how its foods work. The pot is useful for preparing and storing meals that use containers; HC2 meals don't require bowls to craft, and already stack to 64, so passing them through the Cooking Pot would be redundant (and inferior) compared to just crafting them.

I can take a look at other fun interactions sometime, though, such as cuttables. 👍 

> You have to use some items from FD to create fe. spaghetti from Pam's

If by "have" you mean mandatory usage, then no. I'd rather not restrict players as to which things from each mod they should use to make items.
