### ISSUE TITLE
[1.16.5 Suggestion] Create's Sawcutter Compat with cutting board recipes

### ISSUE THREAD

**Issue by Jvs34** [vectorwing/FarmersDelight#267]
I know this can already be done with a Deployer equipped with a tool facing a cutting board, but it is basically a workaround and you have to handle restocking the tools, and if the deployer has an empty hand after a tool is broken, the cutting board puts the ingredient in its hand.

Ideally it would only exports recipes that make sense, such as knife/axe/pickaxe ones.

(And yes I'm aware of the ridiculousness of finely cutting sushi with a giant buzzsaw)

I can prepare a pull request myself if it's fine.

**Comment by DaLumma** [comment]
Imo that doesn't fit at all.

There is already a way to automate the cutting board(with create there are 2) so there is no need for a 3rd.
it feels like the way to automate it currently is too tedious for you so you want to come up with easier solutions that don't make sense to me.

(I hope this doesn't sound rude, if it does it's not intentional)

**Comment by Jvs34** [comment]
Fair enough, it's just that there's some compat already with Create's mixer with stuff like tomato sauce and milling recipes so I thought some deeper integration would've been fine.
