### ISSUE TITLE
Passive Mobs

### ISSUE THREAD

**Issue by dantheman1112** [vectorwing/FarmersDelight#271]
version 1.16.5, super flat world, passive mobs wont spawn but hostile ones will. This could be a problem with the mod or just be a problem with my world. I go to villages and places that should have animals don't. If this isn't a problem with the mod im sorry for any inconvenience I have caused. Besides this, I love this mod so much, please continue to work on this mod.

**Comment by vectorwing** [comment]
Hey there! I'll need more details in order to help you out.

Farmer's Delight does not interact with mob spawning systems at all; assuming your superflat is covered in Grass, my guess is that another mod might be tweaking them.

Please provide your entire mod list, with FD and Forge versions, together with your latest.log if possible. The bug report template has more details.

**Comment by vectorwing** [comment]
I'll be closing the issue for now, as it's a bit stale; feel free to reopen with the information requested above, when you can. 👍
