### ISSUE TITLE
[Suggestion] Serene Seasons crop fertility integration

### ISSUE THREAD

**Issue by ryanaldrich** [vectorwing/FarmersDelight#291]
[Serene Seasons](https://github.com/Glitchfiend/SereneSeasons) is a mod from the Biome's o Plenty team that adds seasons which (among other things) applies fertility modifiers to crop growth based on the current season. Crops grow extremely slowly or not at all when they are not in season. For example wheat is a summer crop, while carrots grow in spring and autumn.

I suggest specifying fertility tags for the new Farmer's Delight crops. The Serene Seasons team has already implemented default support for Farmer's Delight in [this commit](https://github.com/Glitchfiend/SereneSeasons/commit/0a3d8edeae80307e05856da82d9e1a5d86d9aa48), so all Farmer's Delight crops will grow in spring, summer, and autumn. But to customize these seasons and get the in-game tool-tip that displays fertility I think you need to add a set of tags like [these ones](https://github.com/Glitchfiend/SereneSeasons/tree/SS-1.16.x-4.x.x/src/main/resources/data/sereneseasons/tags).

**Comment by vectorwing** [comment]
Thanks for reminding me about it!

From a comment on Curseforge, it seems Serene Seasons is migrating almost entirely to its tags, and they'll be up to owners of crop-adding mods to set. This gives me the chance to pick their seasons, which should be a fun thing to research.

Just gonna drop some mental notes here to read later, but this is open for discussion, if anyone wants to chime in:

- **Cabbage:** I thought of making it evergreen (all seasons) because there's a cabbage type for every season, and it's a crop that lets you get along with few ingredients in a pinch. Would be a good winter companion;
- **Tomato:** Spring and Summer. Tomatoes enjoy a warm climate, I reckon;
- **Onion:** This one is really tricky. From searching many sources, they seem to be both resilient to harsh winter, to preferring cool climates when growing, and/or crossing from cold to warm. So I considered things like Spring/Fall, Winter/Spring and such, but not sure yet;
- **Rice:** I... have no clue! Seems like a Summer/Fall crop, but I could be wrong.

If all else fails, I'll use whatever the SS devs previously set for them.

**Comment by Dradon7** [comment]
After a few minutes of googling, it looks like rice is planted in the spring and harvested in the late summer or fall. You were right about it being a summer/fall thing

**Comment by ryanaldrich** [comment]
My two cents:

It's OK to make things somewhat restrictive, as players are incentivized to build greenhouses to grow things out of season, or to rotate their fields as seasons change. Making an "always fertile" crop defeats the gameplay purpose of fertility.

It's worth noting that snow biomes can only grow winter crops, and hot biomes can NOT grow winter crops, regardless of season (unless a greenhouse is being used).

With that in mind:

- Cabbage: Fall/Winter or just Winter. It's a good winter candidate, but having Fall will allow it to grow in hot biomes.
- Tomato: Summer (only) seems appropriate. They love some heat, and in the Spring season temperate biomes will still have snow and ice on the ground.
- Onion: I'd make them a Spring (only) crop. They like to be planted when it is cool, and develop bulbs when it gets warmer.
- Rice: I also like Summer/Fall. It's a staple crop like wheat.

**Comment by vectorwing** [comment]
Interesting points! I suppose I was going with Spring as a "warmer" climate due to living on the south hemisphere, but I can see how it can have lingering cool weather even then.

Rice seems settled, I feel. Tomato could perhaps be summer-bound, and Cabbage being Fall/Winter seems like an excellent gameplay niche, as it would let it be the "emergency green" and have players spending leftovers on Cabbage Rolls, while not restricting it to snowy biomes.

Onion... hmm. I somehow still don't feel 100% on it being exclusively Spring, but we'll see. Is there any weirdness on it being Fall/Spring, with harsh weathers gapped?

**Comment by vectorwing** [comment]
Commit b39e9dd on `develop-0.5` introduces Serene Seasons tags. They're mostly based from discussions here and on Discord, and might be subject to change. I'll leave the issue open until release, I suppose!

**Comment by vectorwing** [comment]
I released 0.4.6 and forgot to close this. Woops.
