### ISSUE TITLE
[Suggestion] Tables

### ISSUE THREAD

**Issue by GameGibu** [vectorwing/FarmersDelight#292]
Decorative tables on which to serve your feasts!

I believe the addition of decorative tables would fit the theme of Farmer's Delight. Tables are not all that easy to make nicely in vanilla, with the options being generally trapdoors which open, or slabs and stairs which look too thick, and wool for table coverings either needs a full block or an item-blocking carpet on top. My suggestion is to add a dedicated table with spindly legs that could visually connect to other adjacent tables to become a larger table. The thickness of the table might be three pixels and the legs could be anything from inset, two-pixel-wide legs to flush, sturdy 3-pixel-wide legs (the latter sounds easier to model, but what do I know). Additionally, a table cloth could be added by right clicking a bare table with a carpet, consuming it and changing the top and some fraction of the side texture to wool or perhaps a colour-dependent pattern somewhat like llama carpets or the glazed terracotta blocks. Sneaking while placing the carpet would likely be the way to avoid adding the table cloth. This would result in a table with a clear, usable top surface. Breaking a table block with a table cloth on it would drop both the table and the carpet.

I imagine a table would be crafted something like this, with wooden variants:
![image](https://user-images.githubusercontent.com/26589951/124004564-23010500-d9a6-11eb-8a21-3d3fa8ddeff3.png)

I'm not sure if the combination of different wood types and carpets would result in undesirable multiplication of assets, or if the table cloth part can be separated from the wood variants part.

I'm very much enjoying this mod as it is and I understand that this may fall outside of the scope of Farmer's Delight, in some sort of furniture mod instead. When I found the pantry blocks I instantly changed out my barrels and it looks really nice.

**Comment by vectorwing** [comment]
Thanks for sharing the idea!

Yeah, tables are a bit outside the scope of FD, mostly because its decorations are based on the new materials it adds (straw, pretty much).

Pantries are an unique case; although I love them as a block (and I'm happy the community embraced them enough to make variations), I slightly regret adding them on FD, as opposed to a new furniture mod. Mostly because they don't need any FD elements to be made, and were added primarily because "kitchen aesthetics". That and I also derped when naming them, as they should actually be called **cabinets**, with a pantry being an entire room instead. :P

Of course, I didn't have enough ideas for an actual furniture mod, so FD is perhaps a better home for them.
