### ISSUE TITLE
Latest version doesn’t seem to have ham drop

### ISSUE THREAD

**Issue by Shadow212121** [vectorwing/FarmersDelight#293]
Hoglins don’t drop ham

**Comment by vectorwing** [comment]
Please provide more details than just a short sentence. Also, state the version you're in instead of "latest", as sometimes you're not on the latest version.

- Did you deliver a killing blow using a knife from the mod? Or one in `farmersdelight:tools/knives`?
- Did any errors appear in the logs? Please post them here if you can;
- Do you have any datapacks enabled that modify a Hoglin's loot tables?

**Comment by vectorwing** [comment]
I'll be closing this issue since it's gotten stale. Feel free to reopen with the info requested above.
