### ISSUE TITLE
[MC Version] Issue title

### ISSUE THREAD

**Issue by Evo934** [vectorwing/FarmersDelight#299]
**Description**
crash :)

**Steps to reproduce:**
eat banan cookie
Minecraft implodes

**Expected behavior:**
not to implode

**Logs**
check your DMs (Evo#0589)

**Screenshots**
no

**Mod list:**
check your DMs aswell (Evo#0589)

**Comment by CheetahCyberBoi** [comment]
why?

**Comment by Su5eD** [comment]
> check your DMs (Evo#589)

*why* are you posting important information into their DMs rather than posting it here (e.g. using a paste tool)?
This is a public issue tracker, and it's purpose is to let others help out with issues. Such behavior just locks out potential contributors, and decreases the chance of the issue getting fixed.

**Comment by dabomb6405** [comment]
the issue was on cookielicious' side and was fixed lol

**Comment by vectorwing** [comment]
Seems it was indeed fixed on their end, so I'm closing it here. 👍
