### ISSUE TITLE
getting stuck into the ropes rarely

### ISSUE THREAD

**Issue by AbbyGrail** [vectorwing/FarmersDelight#31]
![2020-07-26_23 24 13](https://user-images.githubusercontent.com/65220410/88487035-2cfcd580-cf97-11ea-9a1e-ccc633fae5d2.png)
the player sometimes gets stuck in this situation, the player can get out of the rope, but wont go down.

**Comment by vectorwing** [comment]
Hmm... I couldn't replicate it just yet, but it might be a vanilla issue with the way ladders work.
Scaffolding also has this issue rarely, where it jitters you on very specific positions. Usually, I'd get it when trying to move half-way between a scaffold tower and an extended scaffold arm, but that was because scaffold arms have a bottom "floor" you can stand on. Not sure about this one.

I'll keep an eye on it. 👍

**Comment by vectorwing** [comment]
On a second try, the bug seems to be related to Quark's Fast Ladder Descent. I could replicate it reliably by looking down when between a solid block and the rope.

Since ropes, scaffolding and vines all employ isLadder() from vanilla code, technically they would all be affected. Try disabling it in the config, then testing the issue again.

**Comment by vectorwing** [comment]
Yeah, sadly this is a Quark related issue. Nothing I can do to prevent Fast Ladder stuttering, sorry. :(
