### ISSUE TITLE
[Suggestion] More Fruit Crops

### ISSUE THREAD

**Issue by Flexico** [vectorwing/FarmersDelight#320]
I've just started playing with FD and I'm planning to have it replace Pam's Harvestcraft for my mod collection! However, there are a few things I'll miss, and It would be awesome if you'd be interested in adding a few of them. The main thing is more fruit crops; my favorites are strawberries, bananas, grapes, and peaches! Of course they would come with a few more food items, like a banana split, a PB+J sandwich, or a peach sundae~

Whatever you choose, thanks for sharing your awesome mod! Have a wonderful day~

**Comment by vectorwing** [comment]
Hi there! Glad to hear you're enjoying the mod! ^^

The mod has a low crop count sorta by design., to keep things simple. I mostly couldn't find a lot of interesting gameplay uses around new fruits, so I used the existing ones for them. FD has a somewhat "rustic" theme, so I tend to avoid modern dishes as well.

There might be a fruit or two added in later updates, if I figure out fun things to make out of them. 👍

**Comment by Flexico** [comment]
Aww ok! Thanks for taking the time to read my suggestion~ ^^
