### ISSUE TITLE
Comfort and freezing effect?

### ISSUE THREAD

**Issue by thedocruby** [vectorwing/FarmersDelight#333]
I believe the new freezing effect in Minecraft 1.17 is a good opportunity to improve one of the few things that I dont like about this mod. The wiki article says that the comfort effect prevents the player from getting cold by blocking the slowness effect. This seems backwards to me, because I know that after a good hot meal all I want to do is curl up on the couch and watch movies until I fall asleep. That wouldn't really fall under immune to slowness. However, I do agree that the comfort effect should somehow prevent the player from getting cold to simulate that warm, cozy feeling. That is why I think it would make more sense for comfort to prevent the player from freezing, or at least slow it down like partial leather armor would. This just seems to make more sense, now that it is an option. 

However, I will say that this is just my opinion, and it isn't necessarily shared by the developers, so I will understand if this change never makes it into the mod.

P.S. This mod is probably my favorite Minecraft mod of all time. Thank you for spending the time to keep development moving forward. It means a lot to me, and all the other fans of FD. <3

**Comment by vectorwing** [comment]
Thanks for the feedback! Just for future reference, please open this in the **Discussions** tab next time, as this board is for issues with the mod. ^^

Your wish was granted a few hours ago, on commit a6dfa3c. I'm still ironing out the kinks in the 1.17 port before its release, but Comfort preventing freezing was definitely in the plans ever since its release. 👍

As for it preventing Slowness, it's due to many cold-related mobs and mods using this effect as a representative for cold. Strays, for example, slow you with what's assumed to be a freezing cold shot, due to being snowy skeletons. Comfort is meant both as an indoor pleasure and as a way to endure harsh elements.

That said, I'm not entirely happy with how this effect plays currently, and a redesign is still kinda far due to not knowing which way to go. At least in 1.17 it has a new niche!
