### ISSUE TITLE
[1.16.5] You can make suspicious stew from wild crops

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#358]
**Description**
You can make suspicious stew that doesn't give an effect from wild crops

**Steps to reproduce:**
1. Place down a crafting table
2. input a bowl, brown mushrooms, red mushrooms, and wild crop inside your crafting table
3. it makes sus stew
4. eat that sus stew
5. it gives no effect

**Expected behavior:**
um idfk man, maybe the sus stew should give an effect, maybe you just shouldn't be able to craft it at all 

**Logs**
i doubt it matters so no if you need them i'll provide it

**Screenshots**
no

**Mod list:**
i doubt it matters so no if you need them i'll provide it
FD is 0.5.2, i didn't update it, if you fixed it in the latest on that'd be fun

**Comment by vectorwing** [comment]
This had me looking into the code to realize what was happening, because I certainly did not intend for Wild Crops to be valid for Suspicious Stew. Here's what I found:

- The stew's recipe is dynamic, and considers any `minecraft:small_flowers` valid, regardless of whether they are a `FlowerBlock` class or not;
- Wild Crops are part of `minecraft:small_flowers` to enable Bee interactions (pollination, love mode);
- Minecraft flowers inherit `FlowerBlock`, which asks for a stew effect when instanced. Wild Crops don't use that (I didn't even know this class existed);

Theoretically, I can easily make Wild Crops inherit `FlowerBlock` and specify something. But... I honestly didn't have this in mind at all, let alone what could be their effects. I'll think about it eventually; doesn't seem like I can prevent the stew recipe from considering them valid.

**Comment by vectorwing** [comment]
Commit 418ce6d adds some effects for each Wild Crop, except Rice. This should eventually be backported to 1.16.

**Comment by thelegitdolt** [comment]
nice!
