### ISSUE TITLE
[Suggestion] Table decoration

### ISSUE THREAD

**Issue by MegaGamer265** [vectorwing/FarmersDelight#366]
Plates or placable cups would be nice to decorate our tables! Or tablecloth. And they could have a use too.

**Comment by vectorwing** [comment]
Heyo. I suggest using the **Discussions** tab for suggestions next time, as this board is for problems with the mod. ^^

I considered placeable dining ware in the past, but this would create a huge amount of maintenance each time a meal is introduced, since they would each need custom models/sprites. The Feasts are currently the primary decorative foods of the mod. But thanks for the suggestion!
