### ISSUE TITLE
[1.15.2] Player still takes damage on safety net edge

### ISSUE THREAD

**Issue by Bees-Please** [vectorwing/FarmersDelight#37]
Reproduce: 
In survival, land on edge of safety net with no surrounding blocks

Expected:
Player lands on safety net without taking damage

setup:
![image](https://user-images.githubusercontent.com/65506993/88866814-9e6b9c80-d1c0-11ea-976f-1d4dcbc453ab.png)

min distance that issue will occur:
![image](https://user-images.githubusercontent.com/65506993/88867002-1b971180-d1c1-11ea-9518-525221842b32.png)

gif 1:
![legbreak](https://user-images.githubusercontent.com/65506993/88867121-66188e00-d1c1-11ea-88b9-ed962c2fdc59.gif)

gif 2:
![legbreak2](https://user-images.githubusercontent.com/65506993/88867349-0f5f8400-d1c2-11ea-949e-f38bf0d7d0dd.gif)

Mods list:
Forge 1.15.2 - 31.2.33
FarmersDelight 1.15.2 - 0.1.1

**Comment by vectorwing** [comment]
Hmm... This seems to be another quirk with vanilla methods for these blocks.

`onFallenUpon` and `onLanding` both seem to have the same disparity when checking where you landed: the hitbox governs their call, but they check your _coordinate_ instead of the collided block. So if your hitbox landed by the net, but you were just outside of its full coordinate (net at 1.0 X, you at 0.9 X), the game doesn't think the net was your landing spot, so it never gets the chance to set your fall damage to zero. Vanilla blocks like beds and slime blocks suffer the same problem.

I could probably fix this by doing my own form of hitbox checking, instead of depending on vanilla methods, but not sure how to do that yet, or how hacky it would be. I'll keep this in mind.

**Comment by vectorwing** [comment]
This is a rather old issue, and I couldn't find much on how to fix it for Safety Nets.

There seems to be a config option directly in Forge for changing how bounce collisions are handled (to use hitboxes instead of coordinates), so this seems like a more global problem; I'll be closing it as a "won't fix". Thanks for reporting anyway!
