### ISSUE TITLE
Problem with Turkey cutting from Abnormals

### ISSUE THREAD

**Issue by VHsigil** [vectorwing/FarmersDelight#408]
With Abnormal's & Farmer's Delight installed alongside Autumnity you can make Turkey Pieces by cutting a whole Turkey on a cutting board, right? Well I've found that doing so has some unsolved, immersion breaking issues. Firstly; instead of laying flat on the board like all other items, it stands upright while clipping into the board like so-
![2022-01-30_11 08 06](https://user-images.githubusercontent.com/98708396/151712523-6f48aaaa-44bc-475a-941b-6b07c308ae9e.png)

-and when you go to actually cut it, the particles come up as missing textures.
![2022-01-30_11 08 18](https://user-images.githubusercontent.com/98708396/151712525-58a23650-b419-48ac-bf8c-7ef2ecd65078.png)

I brought this up on the Team Abnormals Discord server and was told this is an issue with Farmer's Delight. Is there a way I could fix this? I don't know if this kind of bugfix would be implemented in the 1.16 versions or reserved for 1.18. I'd rather have it for 1.16 right now than wait for all other mods I love to be updated to 1.18. Cheers.

**Comment by vectorwing** [comment]
Tried it locally just now. It seems that the Cutting Board is considering these to be a 3D block, and is trying to render their sprite as such, instead of a laid-down 2D sprite.

The way the board's rendering works is that, if the GUI render (inventory icon) is a 3D model, it will show it, otherwise it sticks to the 2D sprite. It works for cakes and pies, which are BlockItems, but seems to be confused with the turkey items (which are also placeable blocks).

![image](https://user-images.githubusercontent.com/5566692/160051760-eddbc230-2b03-4e08-b137-f9dff59894d2.png)

The turkey items might be defining their model json's weirdly. I'll do some checking to see if I can figure it out.

**Comment by thelegitdolt** [comment]
by the way this also broken with supplementaries's quivers, which are items by render a 3D block in your hand

**Comment by vectorwing** [comment]
Thanks to some help from XFactHD, we got the bug fixed on render, by applying perspectives before checking `isGui3d()`:

![image](https://github.com/vectorwing/FarmersDelight/assets/5566692/383582f1-3f60-4148-9931-860600885bf6)

This fix should be out in 1.2.2 soon. 👍
