### ISSUE TITLE
Crop Rotation advancement is unobtainable with berry good installed

### ISSUE THREAD

**Issue by Ketok4321** [vectorwing/FarmersDelight#472]
**Description**
Berry good makes sweet and glow berries unplacable, and makes so you need to craft them into pips in order to place them, which doesn't count towards the Crop Rotation advancement.

**Comment by vectorwing** [comment]
Yeah, it's been a common conflict for a while now. 😅

Sadly, there isn't much I can do on my end, since I'd have to keep adding exceptions into the advancement for every mod which prevents placement of vanilla blocks. However, I talked to the Berry Good devs, and they're looking into a potential workaround.
