### ISSUE TITLE
[1.18.2] texture pack issue

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#475]
Changing the template_farmland texture with a resource pack breaks the side texture of the rich soil farmland, which i've seen two resource packs do (hidyk's realm and up to scratch, though up to scratch ended up fixing it on their own), and honestly it doesn't look like that hard of a fix since i managed to fix it on my own so i just figured i'd bring this up

**Comment by vectorwing** [comment]
The problem with resource packs changing template .json's is that they assume a vanilla-only environment.

Usually they change it to do what I do: add custom side textures to farmland. Then, they change farmland directly in accordance to their new template, but ends up breaking other things which depend on those templates being untouched.

Mods can't predict when a resource pack will mess with templates, sadly, and I kinda feel we shouldn't. Anyone changing a vanilla template will run the risk of breaking compatibility; if I manually added models for everything rather than parenting templates, things would become unwieldy. :(

**Comment by thelegitdolt** [comment]
understandable
