### ISSUE TITLE
[MC 1.18.2] Crops are plantable on multiple blocks

### ISSUE THREAD

**Issue by winnetrie83** [vectorwing/FarmersDelight#477]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Crops are plantable on multiple blocks such as grass block and dirt block

**Steps to reproduce:**
Click with a seed on the block( grass, dirt)

**Expected behavior:**
Expecting crops only be plantable on farmland

**Logs**
---File is too big for pastebin---
**Screenshots**
---none---
**Mod list:**
https://pastebin.com/SEk2euJF

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
Chances are you're planting Tomato Seeds. Yes, those are plantable on normal dirt due to being a "berry bush". The crop is pending some redos anyway, so maybe this will change.

If this is happening to any other crop aside from Rice underwater, try making a minimal instance to see if the issue might be some other mod.

**Comment by vectorwing** [comment]
Hi @winnetrie83, is this issue still happening? Have you been able to test other seeds aside from Tomato Seeds?

**Comment by vectorwing** [comment]
I'm closing this issue, as it has gotten stale. Feel free to reply with the requested details, though, if it's still happening.
