### ISSUE TITLE
[MC Version] Issue title

### ISSUE THREAD

**Issue by bumpyJake** [vectorwing/FarmersDelight#484]
**Description**
When players go to get a knife from the creative inventory/JEI menu, their game crashes

**Steps to reproduce:**
Try to get a knife from the creative inventory

**Expected behavior:**
The game should not crash

**Logs**
Game Log - https://pastes.dev/rEcEJYMl85
Server Log - https://pastes.dev/350695iup2

**Screenshots**
Here's a video of the bug happening - https://streamable.com/vl6fqo

**Mod list:**
https://pastes.dev/Zoy8ImbA3U

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
The crash seems to have been caused by **Spartan Weaponry**, while the mod attempted to check an unrecognized tag for throwing weapons. Something might be conflicting weirdly, but I'm not aware of any integration between it and FD's knives.

Please try temporarily disabling Spartan Weaponry, and see if the issue persists in a test world.

**Comment by vectorwing** [comment]
@bumpyJake I wasn't able to replicate this bug locally, but I noticed your pack has a few things you can try checking as well:

- Your version of FD is outdated. Please try updating to version 0.6 and see if the problem persists;
- Try disabling Optifine, as the crash seems to be on the render thread, and it's part of the stacktrace.

Although I'm not updating 1.16.5 anymore, if the issue does happen to be on FD's end, feel free to reopen the issue with your results.
