### ISSUE TITLE
"better" compatibility whit Origin mod

### ISSUE THREAD

**Issue by SerSwett** [vectorwing/FarmersDelight#499]
It would be nice if there was a "better" compatibility whit Origin mod, right now food from farmer's delight that only contain meat aren't label carnivore and so go on for other diets. So race that has specific diets can't eat food from the mod.

**Comment by vectorwing** [comment]
Unless Origins consults some kind of tag to determine carnivorous foods, it should be working. FD's different meat items are marked with `meat()`, which is used by Wolves; this doesn't include Fish, though, as vanilla doesn't mark fish meat as such.

As for meals, I suppose the only truly carnivorous meal in the mod is Bacon and Eggs. Would be funny if it was marked as meat. x)

I'll see if there's anything specific that must be done for foods to be considered diet-friendly on Origins sometime.

**Comment by SerSwett** [comment]
well u could add tags to the foods like Carnivore, vegetarian... and use those tags in the crafting recipe to determin the final diet of the dish.
Ex: only meat recipe = meat food // meat + vegies = omnivore // etc...

**Comment by RaymondBlaze** [comment]
I think you should go to the [Origins (Fabric)](https://github.com/apace100/origins-fabric) for help.

The current carnivore/vegetarian logic only allows a food (defined in the `origins:ignore_diet` tag) to be edible for both powers, instead of allowing it to be not edible for both powers. Also, the current vegetarian has a way larger range of diet as it only refuse to eat "meat". What's worse, some Origins addon is using their own logic and tags, making it impossible to make active support on FD's side only.

Btw, the reason why I'm exclusively suggesting you to go to [Origins (Fabric)](https://github.com/apace100/origins-fabric) is that Origins (Forge) is determined to inherit every feature from the Fabric side, so core logic changes should be requested on the Fabric side in the first place.

**Comment by vectorwing** [comment]
This seems like a fairly elaborate integration, from the looks of it. But thanks for explaining to me where to find resources; I can put this on the backlog for consideration, assuming it can all be done through datapacks. 👍

**Comment by vectorwing** [comment]
I decided to add some Origins compatibility (commit b06cdc3), by populating the `origins:meat` tag with meat items not marked as `meat()` in code. This includes Bacon and Eggs, the only carnivorous meal in FD.

If further compatibility is desired in the future, please open a **discussion** to talk about it. 👍
