### ISSUE TITLE
[1.15.2] Sea beets drop beetroot instead of beetroot seeds

### ISSUE THREAD

**Issue by 00-Steven** [vectorwing/FarmersDelight#50]
**Description**
When breaking sea beets you get beetroots instead of beetroot seeds.

**Steps to reproduce:**
Break a sea beet, get beetroot, be unable to farm more beetroot.

**Expected behavior:**
I expected sea beets to drop beetroot seeds so one could gain the ability to farm beetroots from them.

**Mod list:**
Forge 31.2.26
FarmersDelight-1.15.2-0.1.3.jar

**Comment by vectorwing** [comment]
Hm... I completely forgot they're used in Red Dye instead of being craftable into more seeds. My bad.

I'll change it on 0.1.5, but for now, here's a datapack to modify it on your saves:
[wild_beetroots_drop_seeds.zip](https://github.com/vectorwing/FarmersDelight/files/5048249/wild_beetroots_drop_seeds.zip)

Thanks for letting me know!

**Comment by vectorwing** [comment]
Fixed on commit https://github.com/vectorwing/FarmersDelight/commit/35abcfbeefe44e4a8352fa7d6ce0fa6574a617a2
