### ISSUE TITLE
[1.16.5] Error after mojang loading screen

### ISSUE THREAD

**Issue by adasko7** [vectorwing/FarmersDelight#504]
![issue](https://user-images.githubusercontent.com/89857645/178619564-5583b6bb-76be-405b-8fff-2001deea3274.png)

**Comment by vectorwing** [comment]
Please provide the full logs, accessible from this error screen's buttons below. I can't help figure out the problem without them.

**Comment by adasko7** [comment]
[latest.log](https://github.com/vectorwing/FarmersDelight/files/9097846/latest.log)
[crash-2022-07-13_02.06.40-fml.txt](https://github.com/vectorwing/FarmersDelight/files/9097847/crash-2022-07-13_02.06.40-fml.txt)
Here you go.

**Comment by vectorwing** [comment]
Seems to be a known incompatibility between the mods **Survive** and **Tough as Nails**. Both are attempting to mixin into FoodStats classes, but might be using an outdated class name. FD's load failure was just because it was next on the line.

I recommend trying either mod without the other, and seeing if the issue persists.
