### ISSUE TITLE
[1.18.2 Forge] Compatible with Quark

### ISSUE THREAD

**Issue by BlackAures1** [vectorwing/FarmersDelight#513]
**Description**
When you try to use an iron or diamond hoe (right mouse button) on the grown tomatoes, they start to break and glitter endlessly. The crop is not harvested. But if you use just your bare hand, the crop will be harvested normally. The problem occurs precisely because of the mass harvesting in Quark. All other types of crops are not susceptible to this problem.

**Steps to reproduce:**
1. Take iron or diamond hoe
2. right mouse click on the grown tomatoes 
3. Failure to harvest.
https://youtu.be/2PpjAC_kIZ8

**Logs**
https://drive.google.com/file/d/1uTPWE-6_h7BhC2MWY4Wh3l0W-yRcMRFq/view?usp=sharing

**Mod list:**
[mod list.txt](https://github.com/vectorwing/FarmersDelight/files/9226879/mod.list.txt)

**Comment by vectorwing** [comment]
This happens because Tomato crops are not instances of the `CropBlock` class, which Quark probably looks for.

I chose not to use this class because simple-harvesting mods were overriding the hand-plucking behavior of tomato vines, severely reducing its output and confusing users. However, because of it, mods which check for this class cannot interact with the block either. It's a Catch-22; both issues conflict with one another. 😭

This crop might go through a redesign in upcoming versions, which will allow this to work again. Until then, I don't have a fix for this, sorry.

**Comment by BlackAures1** [comment]
Is it possible to make a config for this? I think modpack creators like me can choose what's best for them. Although if you're going to redo everything, I'm fine with that. It's not a critical bug.
