### ISSUE TITLE
Could you please set a parameter of INVENTORY_SLOT_COUNT?

### ISSUE THREAD

**Issue by Goulixiaoji** [vectorwing/FarmersDelight#517]
https://github.com/vectorwing/FarmersDelight/blob/f9b7cdcbb521349b0e83aa9ce89c4ce71a2c1197/src/main/java/vectorwing/farmersdelight/common/block/entity/StoveBlockEntity.java#L40

**Comment by vectorwing** [comment]
Hi there! What's the use case for this parameter? Are you making an add-on with custom stoves?

**Comment by Goulixiaoji** [comment]
Yes, I am making an add-on mod called Twilight Delight, I need a stove with 8 troughs

**Comment by vectorwing** [comment]
Ah, I see! Hmm... to be honest, I think you might have an easier time just copying the code, or at least extending and overriding most methods in StoveBlockEntity.

The Stove isn't designed to easily change the inventory slot count, because much of its rendering logic depends on it being 6 (item positions and matrices, for example). It doesn't have many utilities to accomodate extra items due to its distinct nature. In fact, much of its code is adapted from the Campfire without directly extending it, since their food-cooking functions are designed to be similar.

Also, since I haven't written a proper API for FD, depending on this class will likely break your add-on frequently during minor updates. I'll see about it, but for now, feel free to copy any part of the Stove's code to fit your needs!

I'm closing this as it's not an issue, but rather a suggestion. But feel free to reply if you want! 👍

**Comment by Goulixiaoji** [comment]
Moreover, is there a public method to get the cutting recipe?
I only found this:
https://github.com/vectorwing/FarmersDelight/blob/c91899f9e6be0ca052c757ef58bea3605924db63/src/main/java/vectorwing/farmersdelight/common/block/entity/CuttingBoardBlockEntity.java#L104
so I use it like [that](https://github.com/Laokuai233/Twilight-Delight/blob/e089065f657a55f42c08b960167c63318620f769/src/main/java/net/twilightdelight/util/FieryClickCuttingBoardUtil.java#L86-L106)

**Comment by vectorwing** [comment]
Recipe checking can be done directly into Minecraft's recipe manager; you don't have to refer to this method directly.

`getMatchingRecipe` is a method which does a caching routine when consulting recipes, so that using the Cutting Board doesn't cause repetitive queries. The relevant bit for finding cutting recipes is this:
https://github.com/vectorwing/FarmersDelight/blob/c91899f9e6be0ca052c757ef58bea3605924db63/src/main/java/vectorwing/farmersdelight/common/block/entity/CuttingBoardBlockEntity.java#L116

If you have an external block or item trying to operate a Cutting Board, you can call `processStoredItemUsingTool`, or mimic a fake player's right-click.

**Comment by Goulixiaoji** [comment]
Ok, thank you!
