### ISSUE TITLE
Suggestion: Make Bottle > Bucket recipes require 4 bottles of the fluid.

### ISSUE THREAD

**Issue by ThugPug43** [vectorwing/FarmersDelight#521]
The current implementation makes sense for FD in a vacuum or in combination with vanilla. However, once tech mods get involved it begins to get messy. Create, for example, assigns each bottle as 250 mb of fluid and each bucket at 1000 mb. This is not uncommon for tech mods. The result is the player can use three bottles of water/milk in Farmer's delight and turn it into a bucket which has enough fluid for 4 bottles. A solution to this would be to require 4 bottles to craft the buckets of fluid rather than the current 3. This would result in a loss when only FD is installed but it will remove milk/water materialization when there are tech mods involved.

**Comment by MarioSMB** [comment]
I'd just like to say I'm all for this change, it fits vanilla (1 honey block takes 4 bottles to make 4 honey bottles).

**Comment by ThugPug43** [comment]
> 

Cauldrons on the other hand are 3 water bottles for 1 bucket so either way there's inconsistency.

**Comment by RaymondBlaze** [comment]
I totally agree with this, especially because I'm working on [both Create and Farmer's Delight](https://github.com/LimonBlaze/creates-delight)
There's less chance having some mod added a milk cauldron than having any kinds of tech mod, and infinite milk is way unacceptable than losing some milk on transport.
Additionally, it would be better to make MilkBottleItem having capabilities about the milk fluid like the BucketItem.

**Comment by vectorwing** [comment]
Hmm yeah, I forgot that Create added this compat from their end.

We were discussing a migration to 1:4 ratios, together with some more shared tags, many of which went live for both mods; but the milk ratio is something I was pushing for a different experiment.

If I make the bucket-to-bottle recipes 1:4, they can no longer be done in the 2x2 crafting grid, which can be frustrating to players. But the bottling recipe itself is already fidgety, because buckets with fluids cannot stack, making this a somewhat moot point.

One concept I was thinking about was implementing a milk jug as a form of fluid tank, to manage not only milk, but any other Forge fluid too. It would make the bottling of milk much easier, as well as perhaps make dough crafting easier as well. But it requires tons of design planning first. 😅

I'll see about changing the bottle-to-bucket recipe in the next update.

**Comment by vectorwing** [comment]
Changed on commit f65d955 for the next release. I'll see about updates to milk bottling in the future.
