### ISSUE TITLE
[MC Version] No version for 1.12.2?

### ISSUE THREAD

**Issue by vipsrbfanpage** [vectorwing/FarmersDelight#529]
Why no for 1.12.2?

**Comment by vectorwing** [comment]
It's answered in the FAQ, on the CurseForge page:

> **Q. Are you going to backport this mod to versions before 1.15?**
> 
> A. No. This mod will never be backported to older versions. The game's older codebases are entirely different, and usually missing important features this mod depends on.
> **Please, do NOT ask for backports!**

1.12.2 is a very old version, with a drastically different codebase than today's versions. It lacks many features FD relies on in order to function. I also don't have enough free time to maintain multiple different codebases, hence why support is dropped as versions advance.

**Comment by vipsrbfanpage** [comment]
Oh my friend wanted it on his server... but most mods are for 1.12.2.. Anyways thanks.
