### ISSUE TITLE
[1.18.2 - Suggestion] Make Tomatoes Need The Rope on The Base

### ISSUE THREAD

**Issue by SaltSouls** [vectorwing/FarmersDelight#555]
So this isn't a bug, but rather a suggestion as I've found the way the tomatoes look when growing up on the rope to be really strange. Rather than making it so that they only need the rope above, maybe make it so they also need it below as well, that way it doesn't look like just a random floating stick above your tomato crop. Otherwise I much prefer this new look for them.

Just an example of what I mean when I say it looks off.
![image](https://user-images.githubusercontent.com/36361103/192176923-8fe87805-c462-4bc6-b1d8-6e038bd4f410.png)

I feel the other thing that could possibly make it look better as well would be making it so the ropes connect, though I understand that would likely be very difficult to do, which is why I feel the other one makes more sense, especially given that tomatoes grow on a vine. So having the bottom support would actually go right in line with how they are normally grown.

**Comment by SaltSouls** [comment]
Side note, I also feel like doing this would make the crop(at least the base) a lot more unique compared to most other crops, as it would be the only one that requires some kinda support to grow.

**Comment by vectorwing** [comment]
The two main reasons why it's currently set this way are:
- Preserving the normal "basic crop" behavior for the bottom plant, making it opt-in and backwards-compatible with old worlds;
- Ropes, being the big thing in FD, make more sense hanging down than actually standing up to the ground.
- The ropes don't connect because it created too much visual clutter, and inflated the blockstates by a lot. :(

Basically, the setup is designed to not only be an optional "extra credit", but also to encourage you to build supports above your crops, further decorating your farm fields in different ways; sort of like how Sweet Berries encourage you to place a low ceiling over them to avoid spikes.

If you want the described behavior, Supplementaries has added compatibility for this mechanic using its own ropes, as well as the placeable sticks; the latter which is able to be attached to the bottom plant. I'd say it's a much more sensible block to accomplish so. 👍

Thanks for the feedback anyway!
