### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by petiteomnivore** [vectorwing/FarmersDelight#559]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Villagers are not replanting various food sources;  cabbage, tomatoes

**Steps to reproduce:**
Created an automated farm with soil planted vegetables, spawned in a villager next to the composter and a hopper minecart to collect the drops underneath the soil.

**Expected behavior:**
Villagers to pick up and replant seeds from the vegetables planted in soil

**Logs**
Even if the game didn't crash, please submit your client/server logs as well. They contain vital information to troubleshoot the issue.

**Screenshots**

**Mod list:**
Better Minecraft 1.19.2 v4

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
This isn't a current feature in the mod, due to this farmer behavior being hardcoded in multiple spots. I tried before, but it didn't work out very well, either for the new crops or for Rich Soil Farmland. :(

In the meantime, I recommend installing [Smarter Farmers](https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant), as it modifies their behavior to encompass any modded crop. 👍
