### ISSUE TITLE
1.19.2: Items placed on Cutting Board are standing up instead of laying flat.

### ISSUE THREAD

**Issue by MonaMoonlight** [vectorwing/FarmersDelight#594]
### Description

Placing items on the cutting board has them stand on end instead of lay flat.
I've tested both food items and things like knives or axes, which do still have the appropriate sneak-place behavior, but also stand on end when placed without sneaking.

### Steps to reproduce

1. Place Cutting Board
2. Place item on Cutting Board

### Mod list

Forge 1.19.2-43.1.57
Farmer's Delight 1.19-1.2.0

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by rckymtnrfc** [comment]
FYI, this is not an issue in Forge 43.1.55 in my testing.

**Comment by vectorwing** [comment]
This is a Forge issue, introduced in version **43.1.56** due to a few rendering changes. `isGui3d()` is returning `true` for all models, when it should only do so for block models; thus, the Cutting Board thinks items are blocks when rendering them.

![image](https://user-images.githubusercontent.com/5566692/209704085-06343e78-9f76-45fb-b532-6c48dd2ab652.png)

I'm looking into a potential workaround, but this fix must be done on their end; seems to be borking other Forge mods too.
You can follow this issue for more updates: https://github.com/MinecraftForge/MinecraftForge/issues/9216

**Comment by rckymtnrfc** [comment]
I believe it's been fixed per this PR - https://github.com/MinecraftForge/MinecraftForge/pull/9231

Thought I'd let you know before you spend too much time on a workaround.

**Comment by vectorwing** [comment]
This bug was fixed on version **43.2.3** of Forge, if anyone is still dealing with it. Please update, and items should be rendered correctly once again. 👍

**Comment by PoipleToitle** [comment]
> This bug was fixed on version **43.2.3** of Forge, if anyone is still dealing with it. Please update, and items should be rendered correctly once again. 👍

I'm currently experiencing this issue, and am running the current version of Forge.
