### ISSUE TITLE
[MC Version]: 1.18.2

### ISSUE THREAD

**Issue by BiankR** [vectorwing/FarmersDelight#599]
### Description

Knife doesn't show on cutting board and items placed on it are under.
Edit: I now noticed the problem is caused by the "Invisible item frame" used for Mizuno's Craft CIT. It would be very nice if the two were compatible, cause a lot of players are now playing with this CIT.

### Steps to reproduce

1. Place cutting board
2. Place item on cutting board (ex: raw porkchop) - showing under / place knife - isn't showing

### Mod list

Using only farmer's delight 1.18.2 - 1.2 and forge for 1.18.2

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Before you edited your issue, I was stumped for a bit, and couldn't replicate it. But yeah, this resource pack is breaking it.

![image](https://user-images.githubusercontent.com/5566692/204527953-d54650e6-8b1c-4935-8dd2-c0cc713e57ba.png)

I have no idea how a resource pack is accomplishing this lower position on Block Renderer stuff, which happens in code; but it's causing every item renderer to be lowered by a pixel or two, affecting other blocks as well. Probably done to not have Item Frame items floating against the surface.

Sadly, this is a quirk on how Mizuno's pack handles things. There isn't a way for FD to be compatible with it, because it apparently affects any vanilla or modded block which renders items. Might be worth contacting the pack developer about this quirk.
