### ISSUE TITLE
load_registrue

### ISSUE THREAD

**Issue by N-Ved** [vectorwing/FarmersDelight#600]
![image](https://user-images.githubusercontent.com/87060868/204621715-b3ce416f-8a93-404e-b870-0b42f47aaa47.png)
Minecraft version 1.16.5
latest.log: https://hastebin.com/qamaziwomi.typescript
crash log: https://hastebin.com/edubidugum.properties

**Comment by vectorwing** [comment]
Sorry for the delay; it seems your logs expired after a month. I don't recommend using Hastebin for sending logs, as they prune old submissions very quickly.

Still, given your screenshot, it really seems like an earlier mod failed to load something, and the error cascaded into other mods, FD included. If the issue is still happening, can you send the log again on [Pastebin](https://pastebin.com)?

**Comment by vectorwing** [comment]
Closing this issue as it's gotten stale. @N-Ved, if the issue is still going, please reply to this issue with the requested logs and I'll reopen it.
