### ISSUE TITLE
[MC Version]: 1.19.2. Shift + clicking non-bowl containers (like glass bottles) in the cooking pot GUI do not place them in the container slot

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#636]
### Description

Shift + clicking non-bowl serving items (like Glass Bottles) in the cooking pot GUI do not place them in the serving slot. 

Since glass bottles are never used in a cooking recipe except as a serving item, they should also be shift-clicked to the cooking pot's serving slot. 

In order to fix this, I suggest two things:
1.  #farmersdelight:serving_items for items that should always be shift-clicked to the containers slot. This should include bowls, glass bottles, and buckets (Both Nether's Delight and Sully's Mod add meals served in buckets)
2. Serving items of the current meal inside the cooking pot will always be shift-clicked to the container slot.

### Steps to reproduce

1. Open Cooking Pot GUI. 
2. Shift Click a glass bottle in your inventory.
3. Notice that it goes inside the food slot instead of the container slot.

### Forge

- [X] I am using the Forge version of Farmer's Delight

**Comment by vectorwing** [comment]
Hmm, this seems like a reasonable check to do. Especially since I have information about both the meal and the recipe cached; it would just have to be present in the client for the GUI to check.

Will take a look later.

**Comment by vectorwing** [comment]
Decided to implement this logic for 1.2.2, as follows:
- Items in the `serving_containers` tag always go into the container slot when shift-clicked;
- If untagged, items are only valid for shift-click if the stored meal is contained in them (for example, Pumpkin). Otherwise, they go into the ingredient slots as usual;

This should cover most use cases swiftly, especially for containers which might also be ingredients. 👍

**Comment by thelegitdolt** [comment]
yippee
