### ISSUE TITLE
[1.19.2]: Pasta recipe does not show up

### ISSUE THREAD

**Issue by racko29** [vectorwing/FarmersDelight#637]
### Description

The pasta recipe does not show up 

### Mod list

Farmer’s delight 1.19-1.2.0
Forge 43.2.0
Journeymap 5.9.3

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
If you mean making Raw Pasta, then you have to use the Cutting Board:

![image](https://github.com/vectorwing/FarmersDelight/assets/5566692/46c27be9-92b7-4ca6-9dd9-d97f52eebff1)

Sadly, due to this workstation's nature, I can't give it the Recipe Book from vanilla, which makes those recipes less intuitive. It's verifiable if you use JEI, but not everyone does. Sorry! ^^

Now, if you mean that you cannot cut Wheat Dough into Raw Pasta, then I might need more details to help you. If so, please post your **logs** here.

**Comment by vectorwing** [comment]
I'm closing this issue, as it's gotten stale. Feel free to reply if the solution above doesn't apply to your case. 👍
