### ISSUE TITLE
[MC Version]: 1.19.2: the JEI usages screen does not show cooking recipes where items are used as containers

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#642]
### Description

The JEI usages screen does not show cooking recipes where items are used as containers.

<img width="840" alt="Screen Shot 2023-02-16 at 1 24 18 PM" src="https://user-images.githubusercontent.com/50085439/219490155-f8f9c2cf-bdad-4c8d-9c1e-c9ad8b338a33.png">
Bowl usage screen (no cooking pot tab)

<img width="882" alt="Screen Shot 2023-02-16 at 1 23 57 PM" src="https://user-images.githubusercontent.com/50085439/219490217-ba04a835-41af-44be-ac3d-974bee3138ae.png">
Pumpkin usage screen (no cooking pot tab)

### Steps to reproduce

1. Install JEI and FD.
2. Locate the bowl item in the JEI screen.
3. Bring up the bowl's usages screen by right clicking or pressing U on the item. 
4. Notice that the JEI pots aren't there.

### Mod list

- Farmer's Delight
- JEI

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by thelegitdolt** [comment]
For some reason, it's in the crafting screen instead?

**Comment by vectorwing** [comment]
Due to some changes in JEI's API, I was unable to let it be treated as an input like before, because it messes with the auto-fill button. Basically, if you use it, this happens:

![image](https://user-images.githubusercontent.com/5566692/235513991-93c258a5-8d9b-4305-9cc7-5f72773a58d9.png)

So I might need to aslk around in JEI's discord to see if I can let containers be "optional" inputs somehow.

**Comment by vectorwing** [comment]
Turns out there is a `CATALYST` role for items in JEI recipe categories, which accomplishes just that: used for lookup, not used for recipe transferring. Should be fixed in the next patch. 👍
