### ISSUE TITLE
[1.19.2]: Farmer's Delight Cooking recipe screens in JEI do not display the XP received and time taken for the recipe

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#649]
### Description

Furnace screen (notice the XP and time readout)
<img width="356" alt="Screen Shot 2023-02-25 at 12 22 34 PM" src="https://user-images.githubusercontent.com/50085439/221378021-823a4666-33cc-4116-a176-2e85f12fbd96.png">

Cooking Screen (No XP or time readout)
<img width="494" alt="Screen Shot 2023-02-25 at 12 22 22 PM" src="https://user-images.githubusercontent.com/50085439/221378027-55994561-8472-41ab-9421-00cacc577f17.png">

### Mod list

Farmer's Delight
JEI

### Logs

Not necessary

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
This was mostly a matter of lacking room in the widget to put this information in. I would need to stretch it a bit, which might prevent JEI from displaying 3 recipes at a time.

**Comment by vectorwing** [comment]
After a lot of iterating, I decided to implement this in the following manner:

![image](https://github.com/vectorwing/FarmersDelight/assets/5566692/39096d24-962a-4d39-a34c-6ec7e464feb9)

The JEI cooking widget does not have enough space to show strings like the furnace widgets have, due to how space is used. Therefore, the progress arrow has a pair of icons for "cook time" and "experience", which display such stats when hovered.

I prefer doing it this way rather than expanding the widget, because it allows for more recipes to be displayed per page. Time and experience are secondary bits of info, so it's not imperative for them to always be visible. A user may notice the widget has icons that the Cooking Pot's GUI lacks, encouraging them to mouse-over if needed.

Anyway, I hope this helps somehow. Should be out in 1.2.2 soon. 😄
