### ISSUE TITLE
[1.18.2]: Rich soil farmland have a texture error on botton 

### ISSUE THREAD

**Issue by RingiTsukitora** [vectorwing/FarmersDelight#669]
### Description

Rich soil farmland have a texture error on botton ,but rich soil not.

### Steps to reproduce

Put rich soil on glass block

### Mod list

FORGE:40.2.0
farmer delight:1.2

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Farmland texture issues are common in instances with resource packs, as some of them change the farmland "template" .json itself. This causes anything using such templates (like FD) to break, since we can't account for their changes.

Please try disabling your resource packs, and see if it persists. If that doesn't work, please send a screenshot of the block.

**Comment by RingiTsukitora** [comment]
> Farmland texture issues are common in instances with resource packs, as some of them change the farmland "template" .json itself. This causes anything using such templates (like FD) to break, since we can't account for their changes.
> 
> Please try disabling your resource packs, and see if it persists. If that doesn't work, please send a screenshot of the block.

Remove resource packs did indeed work, only "dry" farmland have error texture, "wet" farmland not.

**Comment by vectorwing** [comment]
I decided to make my own custom template model for farmland, so that resource packs can't interfere with it. Should be out in the next patch. 👍
