### ISSUE TITLE
Suggestion: Add ice cream

### ISSUE THREAD

**Issue by Unhook** [vectorwing/FarmersDelight#67]
Hey there, love the mod so far! Was wondering if adding ice cream would be something you'd consider (could for example be crafted using a bowl + sugar + milk for the base flavor)?

Thanks in advance.

**Comment by vectorwing** [comment]
Ice Cream is sort of in the drawing board! Especially since it would be a good application for Ice, an often underused material. However, I'd have to measure out flavors and effects first, as a few other mods are already doing wonderful work on the ice cream department, such as MCA's Neapolitan.

Thanks for the idea, though, who knows!

**Comment by COMBOhrenovke** [comment]
It would probably be the best if you make your ice creams a compat with Neapolitan, because making new ice creams in a different way would make this two mods less compatible.

Either way, extra ice creams sounds lovely!

**Comment by EternalShadow17** [comment]
i agree with combo

**Comment by vectorwing** [comment]
@Unhook @COMBOhrenovke @EternalShadow17 

0.3 introduced the Melon Popsicle, a small use for Melons and an emergency food for when you fall into Lava.
I'm not sure if more ice creams will be added, but if any of them involve mods such as Neapolitan, it will probably be made into an add-on. We'll see!

I'll be closing this issue, but just wanted to let you know about it first. 😄
