### ISSUE TITLE
[MC Version]: 1.18.2 No bark from stripping logs

### ISSUE THREAD

**Issue by Aceplante** [vectorwing/FarmersDelight#684]
### Description

If you right click a log to strip it, you do not get bark. As of right now it seems to only be obtained exclusively from the cutting board(?) which is tedious and doesn't make sense.

### Mod list

this one

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Not all players will care about FD on a server. I didn't add Tree Bark to log stripping in-world because builders strip logs often, and it would quickly flood their inventory with an item they might not want or need. FD avoids changing or interfering with vanilla mechanics when possible.

The Cutting Board makes this opt-in, and can be automated with dispensers. I am considering a potential config in the future to introduce in-world Tree Bark as a mechanic, though.
