### ISSUE TITLE
[1.19.2]: Farmer's Delight & Create Mod issue

### ISSUE THREAD

**Issue by Adrian647PH** [vectorwing/FarmersDelight#726]
### Description

Farmer's Delight not compatible with create mod 0.5.1 because Create mod using newer version(4.2.3 forge)

### Steps to reproduce

1. Update it to the newer version

### Mod list

-Farmer's Delight
-Create Mod 0.5.1

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
After testing a few times, both mods boot together fine in a minimal instance, using FD 1.2.1 and Create 0.5.1b.

Since you haven't tested with a minimal instance, chances are you have a Create/FD **add-on** currently installed, such as Create Central Kitchen. Some of those add-ons need to update to accomodate Create's newest version, and CCK in particular is currently causing crashes on load due to incompatibility.

Please provide your full mod list here, as well as any crash logs you have.

**Comment by Adrian647PH** [comment]
> 

Oh.. thanks for letting me know

**Comment by Adrian647PH** [comment]
> > 
> 
> Oh.. thanks for letting me know

Its working now.. i think this issue is fix..

**Comment by vectorwing** [comment]
Nice, good to know! Thanks for the update. ^^
