### ISSUE TITLE
Required minimum Forge version

### ISSUE THREAD

**Issue by jouki** [vectorwing/FarmersDelight#770]
Hello there :)

I know this may be a bit of a pain in the arse, although I'd like to kindly ask whether, by any chance, is possible to make the mod to run on forge version 47.0.35 as this is the version the Optifine (that many users are using due to shaders) is compatible with.
Apologize for a bit "selfish" request, though very much appreciated if fulfilled, and totally understandable if not.

Thank you in advance for your response ^^
Jouki

**Comment by vectorwing** [comment]
Hey there!

Sorry, unfortunately there is a good reason I configured FD to require the recommended build... Forge Beta has a bug where loot modifiers do not apply to entities, breaking the knife's functionality. This is only fixed in Forge 47.0.46, which is already beyond the version you mentioned for Optifine. :(

I suggest either waiting for OF to update, or trying out different performance/shader mods in the meantime, such as Rubidium and Iris. Sorry for the inconvenience!
