### ISSUE TITLE
CRASH - Farmers Delight and Create 

### ISSUE THREAD

**Issue by PhoenixEpic** [vectorwing/FarmersDelight#789]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.0

### Description

Upon loading world after adding Create (1.20.1-0.5.1.d & c) the game will not launch while Create or Farmers Delight are loaded together. Issue also happens with Create is loaded up on its own. Submitting crash report to them as well. 

### Steps to reproduce

Launch game with Create and Farmers Delight

### Mod list

https://pastebin.com/jK13fa8b

### Logs

https://pastebin.com/NEYdSzvs

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by PhoenixEpic** [comment]
I have tested also with just Farmers Delight and Create added to the same pack and it still crashes as well

**Comment by vectorwing** [comment]
Hmm... I was unable to replicate this crash with FD 1.2.3 and Create 0.5.1d on Forge 47.1.0. Not sure what could've happened here.

Are you sre your minimal instance *only* had these two mods when it crashed? Client crashes can sometimes occur with performance and shader mods, so it's important to test without them installed.

**Comment by Chil-Phil** [comment]
I was having issues with Minecraft crashing on attempt to start using FD and Create at the same time and because of this thread only now thought to disable shaders (read: removed OptiFine) and that allowed Minecraft to run.
Since it started fine with Optifine and Farmer's Delight together without Create, I initially thought it was some sort of conflict between FD and Create but now I see that is not the case.
I hope this helps future troubleshooting, and thank you!

**Comment by AranyaMaji** [comment]
I am having the same issue and would like to know how to use both FD and create together while using optifine.

**Comment by vectorwing** [comment]
Sorry folks, but I'm unable to offer support with Optifine-related bugs and crashes. OF is closed-source, and known to meddle with modded rendering in unpredictable ways.

My main suggestion is to try and update OF to any incoming latest versions.
