### ISSUE TITLE
[1.20.1]Cooking Pot Recipes not working on server (famers delight)

### ISSUE THREAD

**Issue by Darlingohaio** [vectorwing/FarmersDelight#799]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.2a / 1.2.3

### Forge version

47.1.0

### Description

Have been playing with friends on athernos server with this mod loaded and suddenly Cooking Pot recipes stopped working (after shutting down server for night we run it again next day and this problem came).

engine - mohist 1.20.1 (344 - unknown)
Farmer's Delight version is 1.2.2a

even when i install 100% the same mode for server and client it's still odesn't work

and I don't know what to do
image

image

image

### Steps to reproduce

1.click on cooking pot
2.press on recipies menu
3.press on dish i want to cook
4.nothing shows up

### Mod list

only farmers delight
and plugins:
FarmProtect-v1.9.0
openinv
Shopkeepers-2.16.5
SimpleTpa
SkinLoader
SkinsRestorer
TreeAssist
UltimateHomes-2.6
worldedit-bukkit-7.2.15

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by bradyyykennyy** [comment]
Same

**Comment by ThisMasquerade** [comment]
Seconded. I cannot find a relevant error message in the output log. The recipes do not display in JEI either

**Comment by sj-hub9796** [comment]
it's not FarmersDelight fault.
please report issue an mohist repo.

**Comment by vectorwing** [comment]
Hello! Sorry for the late reply; this was lost during my hiatus.

I can't really offer much support on server engines such as Mohist, as they have non-standard forge implementations known to break mods.

If the issue is still happening, feel free to post client and server logs, and I may be able to take a look. Also, I suggest forwarding this to Mohist's issue board, as well as update the mod to the 1.2.4 version.
