### ISSUE TITLE
Server Crashing - Dev advice blames FarmersDelight

### ISSUE THREAD

**Issue by Deafpie** [vectorwing/FarmersDelight#847]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.2.0

### Description

I have a server a few friends play on, havent added mods in weeks. Server has run great up until today when 2 friends playing were just digging dirt and stone, and the server crashed 4 times. each crash was about 5 minutes apart, cannot figure out whats causing it. Sent the latest.log to some devs and they said it was farmers delight. 

### Mod list

https://pastebin.com/7WCzRz7S

### Logs

https://pastebin.com/rjBSWLuU

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
If the server itself crashed (players disconnected, server offline), then I will need the server's actual crash log:

```
[05Dec2023 11:48:45.286] [Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/]: This crash report has been saved to: C:\Users\Jared\Desktop\conquest\.\crash-reports\crash-2023-12-05_11.48.45-server.txt
```

This log will have better details regarding what caused the crash. The one you posted doesn't seem to have anything related to FD on it. @Deafpie, please ask your server owner to give you this log, then post it here.

**Comment by vectorwing** [comment]
Hmm, nevermind, the watchdog killed it due to excessive lag. That crash log won't be informative.

@Deafpie, if the issue is still persisting, please ask your server admin to install this mod, **server-side only**:
https://www.curseforge.com/minecraft/mc-mods/fullstack-watchdog

In case it crashes again, this mod will make the logs will have better info on what caused it. Your current logs don't seem to point to any causes for the watchdog trigger.

**Comment by vectorwing** [comment]
I'm closing this issue, as it has gotten stale.
Feel free to reopen and reply with the info requested above, if it's still happening. 👍
