### ISSUE TITLE
Farmer Tomato

### ISSUE THREAD

**Issue by Kiryuumaru** [vectorwing/FarmersDelight#878]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.2.0

### Description

Great mod btw. I want to make the minecolonies farmer to farm tomato. but farmer does not plant it, they just walk around the tomato field. Farmers are able to plant other plantables in this mod, except tomato. Is there any workaround on this?

### Mod list

Minecolonies official modpack

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
When MineColonies farmers attempt to plant or harvest a crop, they check if the block is an `instanceof CropBlock`. Due to how the tomato crop functions (being pickable when mature, growing ropes etc), its earliest stage is not a CropBlock, but the later stages are.

This causes the farmer to fail planting, but it will be able to harvest fully grown tomato bushes by breaking them.

This isn't something I have much control over, as it depends on the way Minecolonies checks for crops. You could try forwarding this issue to the MineColonies team.
