### ISSUE TITLE
server crashing, possible mod conflict?

### ISSUE THREAD

**Issue by Emmulah** [vectorwing/FarmersDelight#888]
### Minecraft version

1.19.2

### Farmer's Delight version

1.2.4

### Forge version

43.3.5

### Description

farmer's delight is listed as a potential culprit for this crash, along with hexerei (this has been reported to them also). 

### Steps to reproduce

this happens upon login near rich soil, possibly with hexerei plants planted in it.

### Mod list

listed in crash report

### Logs

https://paste.ee/p/pNwDc

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Ah, this is a similar issue to what another biome mod had!

The issue lies with Hexerei, and how its crop blocks define their bonemeal behavior. Their code is likely not checking if the plant is mature before setting the blockstate, because the plants are right-click-harvested before it happens.

Please follow the issue you opened on Hexerei for a solution, as there isn't a fix I can apply from my end. 👍
