### ISSUE TITLE
[1.16.4] Dog food item

### ISSUE THREAD

**Issue by BedrockLegends** [vectorwing/FarmersDelight#90]
**Description**
As soon as I launcher my custom pack on the new 1.16.3 version of this mod, it crashes straight to desktop
**Steps to reproduce:**
What did you do to cause the issue? Can it be replicated?
Nothing just updated the mod and crashed
**Expected behavior:**
A Fix
[crash-2020-12-01_20.53.30-client.txt](https://github.com/vectorwing/FarmersDelight/files/5626688/crash-2020-12-01_20.53.30-client.txt)

**Screenshots**

**Mod list:**
Post a list of your mods here, **Forge and Farmer's Delight versions are mandatory!**
You can generate a mod list by forcing a crash. In your game, hold F3+C for 10 seconds, then check your logs; the list of mods will be by the end.

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
Seems IntelliJ auto-completed the wrong Pair object when I was porting... At least it's an easy fix.
Thanks for letting me know, I'll post an update soon. 👍

**Comment by vectorwing** [comment]
I could not replicate your issue, but I fixed the faulty import. FD **1.16.3-0.2.4a** is up on Curseforge. Please try it out and let me know if the issue is fixed.

https://www.curseforge.com/minecraft/mc-mods/farmers-delight/files/3128249

Also, please try to make a minimal instance to help debug the issue next time, or try to remove mods to see if the issue persists. Helps a ton with debugging.
