### ISSUE TITLE
Pumpkin recipes don't use the `forge:pumpkins` item tag

### ISSUE THREAD

**Issue by Insane96** [vectorwing/FarmersDelight#909]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.20

### Description

The following recipes don't use the `forge:pumpkins` item tag

* `cutting/pumpkin`
* `stuffed_pumpkin_block`

### Mod list

No need

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Both cases are somewhat intended:
- `cutting/pumpkin` yields 4 Pumpkin Slices. I'm not sure which other pumpkin-like items will be added to this tag, and whether they should be yielding that many slices, so I resorted to only the vanilla Pumpkin. It's better to create unique recipes for their use cases instead;
- `stuffed_pumpkin_block` uses Pumpkins as a container. Currently, the Cooking Pot does not allow tags for containers, only specific items, since it would potentially cause item conversions when extracting and eating servings. This is being considered for a change in the future.

**Comment by Insane96** [comment]
> I'm not sure which other pumpkin-like items will be added to this tag

Autumnity adds another pumpkin (the giant ones) that are made in a 1:1 ratio. Atm I don't know any other mod that adds pumpkins to that tag
