### ISSUE TITLE
Tomato Vines on rope can randomly pop off/rope vanishes

### ISSUE THREAD

**Issue by Inonedn** [vectorwing/FarmersDelight#955]
### Minecraft version

1.20.1 and 1.21

### Farmer's Delight version

1.2.4

### Forge version

145

### Description

When growing a tomato vine on a rope, sometimes the rope disappears, leaving nothing behind, eventually popping off the tomato vine too. It will do this regardless of light level or circumstances

### Steps to reproduce

1. Grow a tomato vine on a rope
2. Wait for it to eventually pop off

### Mod list

N/A

### Logs

N/A

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
I haven't been able to replicate this issue on my end. Even after growing roped tomatoes on both types of farmland, either by accelerated random ticks or bone meal, none of them ever popped off, or grew without the rope.

Are you sure this is on a minimal instance? Can you provide a video or screenshot of it happening?

![image](https://github.com/user-attachments/assets/26213e3a-2aaa-486a-9ecb-e375afc2499b)

> 145

Please post the complete Forge or NeoForge version, not just the number.

**Comment by vectorwing** [comment]
Forgot to update here: this issue is explicitly caused by bees pollinating Tomato Vines. When they pollinate, their code tries to set only the `age` state, resetting `ropelogged` back to `false`. This deletes the rope and causes the block to be unstable, breaking on the next block update.

For now, the only fix I can apply is to remove `tomatoes` from crop tags, thus making them invalid for bee pollination. The issue may be fully solved if I manage to revisit this block to have a separate roped variant, rather than a blockstate.

**Comment by vectorwing** [comment]
A workaround was added in commit c596b1d. As said above, I'm testing a rework for the crop that may fix this completely later.
