### ISSUE TITLE
Cabbage always produces cabbage rolls in the pot

### ISSUE THREAD

**Issue by yzqdev** [vectorwing/FarmersDelight#999]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### NeoForge version

47.3.11

### Description

as seen in the video, when clicking the recipe from the list and manually placing the ingredients in the pot, cabbage rolls come out.

https://github.com/user-attachments/assets/0676ea25-cc02-4518-a7d4-c21b8f9bd387

### Mod list

the mod list pastebin url->
https://pastebin.ubuntu.com/p/cf8BfCXCD6/

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
This bug is caused by the **Autochefs Delight** addon. It modifies the Cooking Pot's recipe check to read stack sizes, but it's not accounting for "broad vs specific" recipe conflicts.

Cabbage Roll accepts all three of these non-cabbage ingredients as a "filling", so it's still considering the rolls as a valid recipe to cook. Since it's already matching this recipe, it never attempts to make Vegetable Soup; the current one takes priority.

I suggest reporting this to the add-on's issue board instead: https://github.com/Snownee/AutochefsDelight/issues
